name: 'PR Chatter'
author: 'Brian Mitchell <bman4789@gmail.com>'
description: 'Add fun chatter to your Pull Requests.'
branding:
  icon: 'gift'
  color: 'purple'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  GITHUB_TOKEN:
    description: 'Github Token for authentication'
    required: true
