name: Self-Test

on:
  pull_request:
    branches: [main]
  pull_request_review:
    types: [submitted, dismissed]
    branches: [main]

jobs:
  main:
    runs-on: ubuntu-latest
    name: Main
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: PR Chatter step
        uses: ./ # Uses an action in the root directory
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
